query CodeEditorData @loading {
	geos @loading {
		xmlSchema @loading {
			simpleTypes @loading {
				name 
				pattern 
			}
			complexTypes @loading {
				name 
				attributes  {
					name 
					type 
					required
					default
					pattern
				}
				childTypes 
			}
		}
	}
}