query GetXmlSchema {
  geos {
    xmlSchema {
      simpleTypes {
        name
        pattern
      }
      complexTypes {
        name
        attributes {
          name
          type
          required
          default
          pattern    
        }
        childTypes
      }
    }
  }
}