mutation UpdateGraph($updateGraphInput: GraphUpdateInput!) {
    graph {
        updateGraph(graphUpdateInput: $updateGraphInput) {
            id
            name
            description
            isPublic
        }
    }
}