query GraphEditorData {
	geos @loading {
		typesTree @loading
		typesPaths @loading
		xmlSchema @loading {
			simpleTypes @loading {
				enum
				name
				pattern
			}
			complexTypes @loading {
				link
				name
				attributes {
					description
					name
					type
					required
					default
				}
				childTypes
			}
		}
	}
}
